default_config:

tts: !include tts.yaml
scene: !include scenes.yaml
automation: !include automations.yaml

script: !include_dir_named scripts/
device_tracker: !include_dir_list device_tracker/
binary_sensor: !include_dir_merge_list binary_sensors/